//
// SharedPrefsStorage.kt
// Rift SDK
//
// Hand-written SharedPreferences-backed implementation of the `RiftStorage`
// foreign trait generated by UniFFI. Not generated — do not overwrite.
//
// This storage backend persists the Rift SDK's install_id and user
// binding state across app launches. On Android, app data is wiped on
// uninstall by design, so unlike iOS Keychain the install_id does NOT
// survive reinstallation. For fresh-install attribution, rely on Google
// Play Install Referrer (orthogonal to this file).
//
// Uses standard `SharedPreferences` with MODE_PRIVATE. No new dependencies
// required. The OS already sandboxes the prefs file per-app, and the
// values stored (install UUID + user ID) don't warrant encryption at rest.
//

package ink.riftl.sdk

import android.content.Context

public class SharedPrefsStorage(
    context: Context,
    prefsName: String = "rift_sdk_prefs"
) : RiftStorage {
    private val prefs = context.applicationContext
        .getSharedPreferences(prefsName, Context.MODE_PRIVATE)

    override fun `get`(key: String): String? {
        return try {
            prefs.getString(key, null)
        } catch (e: Exception) {
            throw StorageError.IoError(
                message = "shared prefs read failed: ${e.message}"
            )
        }
    }

    override fun `set`(key: String, value: String) {
        try {
            prefs.edit().putString(key, value).apply()
        } catch (e: Exception) {
            throw StorageError.IoError(
                message = "shared prefs write failed: ${e.message}"
            )
        }
    }

    override fun remove(key: String) {
        try {
            prefs.edit().remove(key).apply()
        } catch (e: Exception) {
            throw StorageError.IoError(
                message = "shared prefs delete failed: ${e.message}"
            )
        }
    }
}

/**
 * Create a RiftSdk with sensible Android defaults: SharedPreferences-backed
 * storage, app version auto-read from PackageManager, and no custom base URL.
 *
 * ```kotlin
 * val rift = RiftSdk.create("pk_live_...", applicationContext)
 * ```
 */
fun RiftSdk.Companion.create(
    publishableKey: String,
    context: Context,
    conversionSourceUrl: String? = null
): RiftSdk {
    val version = try {
        context.packageManager.getPackageInfo(context.packageName, 0).versionName
    } catch (e: Exception) {
        "unknown"
    }
    // Scope SharedPreferences by publishable key prefix so multiple apps
    // using different Rift tenants on the same device don't share state.
    val keyPrefix = publishableKey.take(16)
    return RiftSdk(
        config = RiftConfig(
            publishableKey = publishableKey,
            baseUrl = null,
            logLevel = null,
            conversionSourceUrl = conversionSourceUrl,
            appVersion = version
        ),
        storage = SharedPrefsStorage(context, prefsName = "rift_sdk_$keyPrefix")
    )
}
