//
// SharedPrefsStorage.kt
// Rift SDK
//
// Hand-written SharedPreferences-backed implementation of the `RiftStorage`
// foreign trait generated by UniFFI. Not generated — do not overwrite.
//
// This storage backend persists the Rift SDK's install_id and user
// binding state across app launches. On Android, app data is wiped on
// uninstall by design, so unlike iOS Keychain the install_id does NOT
// survive reinstallation. For fresh-install attribution, rely on Google
// Play Install Referrer (orthogonal to this file).
//
// Uses standard `SharedPreferences` with MODE_PRIVATE. No new dependencies
// required. The OS already sandboxes the prefs file per-app, and the
// values stored (install UUID + user ID) don't warrant encryption at rest.
//

package ink.riftl.sdk

import android.content.Context

public class SharedPrefsStorage(context: Context) : RiftStorage {
    private val prefs = context.applicationContext
        .getSharedPreferences("rift_sdk_prefs", Context.MODE_PRIVATE)

    override fun `get`(key: String): String? {
        return try {
            prefs.getString(key, null)
        } catch (e: Exception) {
            throw StorageException.IoError(
                message = "shared prefs read failed: ${e.message}"
            )
        }
    }

    override fun `set`(key: String, value: String) {
        try {
            prefs.edit().putString(key, value).apply()
        } catch (e: Exception) {
            throw StorageException.IoError(
                message = "shared prefs write failed: ${e.message}"
            )
        }
    }

    override fun remove(key: String) {
        try {
            prefs.edit().remove(key).apply()
        } catch (e: Exception) {
            throw StorageException.IoError(
                message = "shared prefs delete failed: ${e.message}"
            )
        }
    }
}
