import { buildPricingMarkdown } from "@/lib/tiers";

export const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL || "https://riftl.ink";
export const apiUrl =
  process.env.NEXT_PUBLIC_API_URL || "https://api.riftl.ink";

export function buildDocsLlmsText(): string {
  return [
    "# Riftl.ink Docs",
    "",
    "Scoped documentation context for Riftl.ink developer docs.",
    "",
    "## Primary Guides",
    "",
    `- Quick Start: ${siteUrl}/docs`,
    `- Manual Setup: ${siteUrl}/docs/manual-setup`,
    `- Links: ${siteUrl}/docs/links`,
    `- Webhooks: ${siteUrl}/docs/webhooks`,
    `- Conversions: ${siteUrl}/docs/conversions`,
    `- Publishable Keys: ${siteUrl}/docs/publishable-keys`,
    `- MCP Server: ${siteUrl}/docs/mcp`,
    "",
    "## When To Use",
    "",
    "- Use these docs when setting up Riftl.ink manually or integrating specific product areas.",
    "- Prefer the MCP guide when the host already supports MCP tools.",
    "- Prefer the API reference when generating code from OpenAPI.",
    "",
  ].join("\n");
}

export function buildApiLlmsText(): string {
  return [
    "# Riftl.ink API",
    "",
    "Scoped API context for Riftl.ink machine-readable integrations.",
    "",
    "## Endpoints",
    "",
    `- OpenAPI: ${siteUrl}/openapi.json`,
    `- Well-Known OpenAPI: ${siteUrl}/.well-known/openapi.json`,
    `- API Catalog: ${siteUrl}/.well-known/api-catalog`,
    `- MCP Endpoint: ${apiUrl}/mcp`,
    `- MCP Manifest: ${siteUrl}/.well-known/mcp.json`,
    `- Health: ${apiUrl}/health`,
    "",
    "## Auth",
    "",
    "- Bearer tokens use rl_live_ secret keys.",
    "- Publishable keys use the pk_live_ prefix and are limited to attribution flows.",
    "",
    "## Agent Guidance",
    "",
    "- Use Accept: application/json when resolving links as an agent.",
    "- Use MCP when the host supports native tool calling.",
    "",
  ].join("\n");
}

export function buildLlmsText(): string {
  return [
    "# Riftl.ink (Rift)",
    "",
    "> Deep linking and attribution API. Built for humans, ready for agents. One link, two audiences: humans click and get redirected, agents resolve the same URL into structured JSON.",
    "",
    "## Product",
    "",
    "Riftl.ink is API-first link infrastructure for iOS, Android, and web. Rift handles short links, deep links, deferred deep linking, install attribution, and conversion tracking. Developer resources for Rift are published on `riftl.ink` and `api.riftl.ink`.",
    "",
    "Pricing is usage-based with a free tier and paid plans for higher traffic and longer retention. Sign up, get an `rl_live_` API key, and POST to `/v1/links`.",
    "",
    "## Developer Resources",
    "",
    `- [OpenAPI JSON](${siteUrl}/openapi.json): machine-readable API schema for Rift`,
    `- [Well-Known OpenAPI](${siteUrl}/.well-known/openapi.json): predictable OpenAPI URL for agents`,
    `- [API Catalog](${siteUrl}/.well-known/api-catalog): RFC 9727 linkset catalog for Rift APIs`,
    `- [API Reference](${siteUrl}/api-reference): human-readable OpenAPI-backed reference`,
    `- [MCP Endpoint](${apiUrl}/mcp): Rift Model Context Protocol server for agents`,
    `- [MCP Manifest](${siteUrl}/.well-known/mcp.json): MCP Registry-style server metadata for Rift`,
    `- [MCP Docs](${siteUrl}/docs/mcp): how agents should use the Rift MCP server`,
    `- [Health Check](${apiUrl}/health): API status endpoint`,
    "",
    "## Use Cases",
    "",
    "- Create deep links that work for both humans and AI agents",
    "- Resolve a single link as a browser redirect or as structured JSON",
    "- Attach machine-readable `agent_context` to links",
    "- Track clicks, installs, attribution, and conversion events",
    "- Expose link creation and management through MCP tools for LLM clients",
    "",
    "## When To Use Rift",
    "",
    "- Use Rift when an agent needs to generate or inspect deep links programmatically",
    "- Use Rift when the same URL must serve browsers and AI clients differently",
    "- Use Rift when attribution and conversion tracking need to stay tied to the link lifecycle",
    "- Use Rift MCP for interactive agent workflows inside Claude, ChatGPT, or other MCP hosts",
    "",
    "## When Not To Use Rift",
    "",
    "- Do not use Rift as a general file store, CMS, or long-form content host",
    "- Do not use Rift as an OAuth provider or identity platform",
    "- Do not use Rift as a generic workflow engine unrelated to links, routing, or attribution",
    "",
    "## Docs",
    "",
    `- [Quick Start](${siteUrl}/docs): CLI and manual setup paths to a working link in ~30 seconds`,
    `- [Manual Setup](${siteUrl}/docs/manual-setup): raw HTTP setup path for developers and agents`,
    `- [Links](${siteUrl}/docs/links): create, update, and resolve deep links`,
    `- [Attribution](${siteUrl}/docs/attribution): click, install, and user attribution`,
    `- [Conversions](${siteUrl}/docs/conversions): post-install event tracking`,
    `- [Webhooks](${siteUrl}/docs/webhooks): outbound event delivery and signature verification`,
    `- [Deferred Deep Linking](${siteUrl}/docs/deferred): route users into the app after install`,
    `- [Universal Links](${siteUrl}/docs/universal-links): iOS and Android app-link setup`,
    `- [Domains](${siteUrl}/docs/domains): primary and alternate custom domains`,
    `- [Apps](${siteUrl}/docs/apps): registering iOS and Android apps`,
    `- [Publishable Keys](${siteUrl}/docs/publishable-keys): client-side SDK keys`,
    `- [iOS SDK](${siteUrl}/docs/ios-sdk)`,
    `- [Android SDK](${siteUrl}/docs/android-sdk)`,
    `- [Web SDK](${siteUrl}/docs/web-sdk)`,
    "",
    "## Authentication",
    "",
    `- [Quick Start](${siteUrl}/docs): create an account and get a Rift API key`,
    "- Authentication uses Bearer tokens with secret keys that start with `rl_live_`",
    "- Client-side SDKs use publishable keys that start with `pk_live_`",
    `- [Publishable Keys](${siteUrl}/docs/publishable-keys): client-side SDK key management`,
    "",
    "## Agent Workflow",
    "",
    `1. Discover the API at [OpenAPI JSON](${siteUrl}/openapi.json) or [API Catalog](${siteUrl}/.well-known/api-catalog)`,
    "2. Authenticate with a Bearer token using an `rl_live_` secret key",
    `3. Create links with \`POST ${apiUrl}/v1/links\``,
    "4. Resolve links with `Accept: application/json` when the caller is an agent",
    `5. Use MCP at \`${apiUrl}/mcp\` when the host supports MCP tools directly`,
    "",
    "## Constraints",
    "",
    "- Secret keys are server-side credentials and must not be exposed in client code",
    "- Publishable keys are limited to attribution and conversion endpoints",
    "- Custom IDs require a verified custom domain",
    "- Some workflows depend on mobile app setup, domain verification, or webhook receivers outside Rift",
    "",
    "## Integrations",
    "",
    `- [Webhooks](${siteUrl}/docs/webhooks): click, attribution, and conversion events`,
    `- [MCP Endpoint](${apiUrl}/mcp): create and manage Rift links from MCP clients`,
    `- [MCP Manifest](${siteUrl}/mcp/server.json): machine-readable MCP server metadata`,
    `- [Apps](${siteUrl}/docs/apps): iOS and Android app association setup`,
    "",
    "## Optional",
    "",
    `- [Sitemap](${siteUrl}/sitemap.xml)`,
  ].join("\n");
}

export function buildLlmsFullText(): string {
  return [
    buildLlmsText(),
    "",
    "## Scoped Context",
    "",
    buildDocsLlmsText(),
    "",
    buildApiLlmsText(),
    "",
    "## Pricing",
    "",
    buildPricingMarkdown(),
  ].join("\n");
}

export function buildIndexMarkdown(): string {
  return [
    "# Riftl.ink",
    "",
    "Deep links for humans and agents.",
    "",
    "Riftl.ink is API-first link infrastructure for iOS, Android, and web. Humans can click a link and get redirected into the right app or web destination. Agents can resolve the same link into structured JSON and use the attached context programmatically.",
    "",
    "## Key Resources",
    "",
    `- Docs: ${siteUrl}/docs`,
    `- API Reference: ${siteUrl}/api-reference`,
    `- OpenAPI: ${siteUrl}/openapi.json`,
    `- API Catalog: ${siteUrl}/.well-known/api-catalog`,
    `- MCP Docs: ${siteUrl}/docs/mcp`,
    `- MCP Endpoint: ${apiUrl}/mcp`,
    `- Pricing: ${siteUrl}/pricing.md`,
    `- llms.txt: ${siteUrl}/llms.txt`,
    "",
    "## Use Cases",
    "",
    "- Deep links for mobile and web journeys",
    "- Agent-readable link routing",
    "- Install attribution and conversion tracking",
    "- MCP-native link management for AI tools",
    "",
  ].join("\n");
}
